### ISSUE TITLE
set PHP version in composer.json to 8.1 or 8.2

### ISSUE THREAD

**Issue by ismaail** [Zakarialabib/Mystock-Laravel-Livewire-alpine-tailwind-Inventory-Pos#17]
to take advantage of [8.1](https://www.php.net/releases/8.1/en.php) new features (specialy Enums)

**Comment by Zakarialabib** [comment]
issue solved in this `[commit](https://github.com/Zakarialabib/Mystock-Laravel-Livewire-alpine-tailwind-Inventory-Pos/commit/8701ad07bb43124709dca375acddaaee3bbc7ce8)`
