### ISSUE TITLE
branches name confusion

### ISSUE THREAD

**Issue by ismaail** [Zakarialabib/Mystock-Laravel-Livewire-alpine-tailwind-Inventory-Pos#23]
now there is **main** & **master**, which one is the principal branch ? 

there should be only one principal branch **main** or **master**.

if you want to work with 2 branches, one for development & one for production, then choose:
- `main` & `develop`
or 
- `master` & `develop`

**Comment by Zakarialabib** [comment]
i moved latelty from main to master, main gets repeated in diffrent places i though about changed it , now main is deleted,

**Comment by ismaail** [comment]
it's better to choose just one of theme, and use it in all your projects.
